WITH 
WINDOWS AS (
	SELECT id, dn_id, is_r, rcode, macsrc, macdst, FLOOR(SECONDS/3600) as hour FROM message3_it2016_0
	WHERE FLOOR(SECONDS/3600) BETWEEN 0 AND 2
),
TMP AS (
	SELECT
	0 AS "day",
	hour AS "hour",
	dn.dac_family_rank1 AS DAC_FAMILY,
	
	COUNT(*) AS QR,
	COUNT(*) FILTER (WHERE IS_R IS FALSE) AS Q,
	COUNT(*) FILTER (WHERE RCODE = 0) AS OK,
	COUNT(*) FILTER (WHERE RCODE = 3) AS NX,
	COUNT(*) FILTER (WHERE NOT dn.regex_check) AS QR_NOTVALID,
	COUNT(*) FILTER (WHERE IS_R IS FALSE AND NOT dn.regex_check) AS Q_NOTVALID,
	COUNT(*) FILTER (WHERE RCODE = 3 AND NOT dn.regex_check) AS NX_NOTVALID,
	COUNT(*) FILTER (WHERE RN=1) AS FA,
	COUNT(*) FILTER (WHERE RCODE=0 AND RN_QR_RCODE=1) AS FA_OK,
	COUNT(*) FILTER (WHERE RCODE=3 AND RN_QR_RCODE=1) AS FA_NX,
	COUNT(*) FILTER (WHERE RN_MAC=1) AS MACFA,
	COUNT(*) FILTER (WHERE RCODE=0 AND RN_MAC_QR_RCODE=1) AS MACFA_OK,
	COUNT(*) FILTER (WHERE RCODE=3 AND RN_MAC_QR_RCODE=1) AS MACFA_NX,


	COUNT(DISTINCT DN_ID) FILTER (WHERE P1) AS  P1_DN,
	COUNT(DISTINCT DN_ID) FILTER (WHERE NOT dn.regex_check AND P1) AS  P1_DN_NOTVALID,
	COUNT(DISTINCT DN_ID) FILTER (WHERE RCODE=0 AND P1) AS  P1_DN_OK,
	COUNT(DISTINCT DN_ID) FILTER (WHERE RCODE=3 AND P1) AS  P1_DN_NXD,
	COUNT(DISTINCT DN_ID) FILTER (WHERE RCODE=3 AND NOT dn.regex_check AND P1) AS  P1_DN_NXD_NOTVALID,
	COUNT(*) FILTER (WHERE P1) AS  P1_QR,
	COUNT(*) FILTER (WHERE IS_R IS FALSE AND P1) AS  P1_Q,
	COUNT(*) FILTER (WHERE RCODE = 0 AND P1) AS  P1_OK,
	COUNT(*) FILTER (WHERE RCODE = 3 AND P1) AS  P1_NX,
	COUNT(*) FILTER (WHERE NOT dn.regex_check AND P1) AS  P1_QR_NOTVALID,
	COUNT(*) FILTER (WHERE IS_R IS FALSE AND NOT dn.regex_check AND P1) AS  P1_Q_NOTVALID,
	COUNT(*) FILTER (WHERE RCODE = 3 AND NOT dn.regex_check AND P1) AS  P1_NX_NOTVALID,
	COUNT(*) FILTER (WHERE RN=1 AND P1) AS  P1_FA,
	COUNT(*) FILTER (WHERE RCODE=0 AND RN_QR_RCODE=1 AND P1) AS  P1_FA_OK,
	COUNT(*) FILTER (WHERE RCODE=3 AND RN_QR_RCODE=1 AND P1) AS  P1_FA_NX,
	COUNT(*) FILTER (WHERE RN_MAC=1 AND P1) AS  P1_MACFA,
	COUNT(*) FILTER (WHERE RCODE=0 AND RN_MAC_QR_RCODE=1 AND P1) AS  P1_MACFA_OK,
	COUNT(*) FILTER (WHERE RCODE=3 AND RN_MAC_QR_RCODE=1 AND P1) AS  P1_MACFA_NX,

	SUM(LOGIt1) AS LLR1_QR,
	SUM(LOGIt1) FILTER (WHERE IS_R IS FALSE) AS LLR1_Q,
	SUM(LOGIt1) FILTER (WHERE RCODE = 0) AS LLR1_OK,
	SUM(LOGIt1) FILTER (WHERE RCODE = 3) AS LLR1_NX,
	SUM(LOGIt1) FILTER (WHERE NOT dn.regex_check) AS LLR1_QR_NOTVALID,
	SUM(LOGIt1) FILTER (WHERE IS_R IS FALSE AND NOT dn.regex_check) AS LLR1_Q_NOTVALID,
	SUM(LOGIt1) FILTER (WHERE RCODE = 3 AND NOT dn.regex_check) AS LLR1_NX_NOTVALID,
	SUM(LOGIt1) FILTER (WHERE RN=1) AS LLR1_FA,
	SUM(LOGIt1) FILTER (WHERE RCODE=0 AND RN_QR_RCODE=1) AS LLR1_FA_OK,
	SUM(LOGIt1) FILTER (WHERE RCODE=3 AND RN_QR_RCODE=1) AS LLR1_FA_NX,
	SUM(LOGIt1) FILTER (WHERE RN_MAC=1) AS LLR1_MACFA,
	SUM(LOGIt1) FILTER (WHERE RCODE=0 AND RN_MAC_QR_RCODE=1) AS LLR1_MACFA_OK,
	SUM(LOGIt1) FILTER (WHERE RCODE=3 AND RN_MAC_QR_RCODE=1) AS LLR1_MACFA_NX

	FROM WINDOWS M
	JOIN bigdn_m3_3 DN ON M.DN_ID=DN.ID
	JOIN M3_RN ON M3_RN.id=M.ID
	GROUP BY "day", hour, DAC_FAMILY
)
SELECT l.*, tmp.* FROM tmp JOIN get_hourdn_statistics(tmp.dac_family, tmp.hour::int) as l ON tmp.dac_family=l.dac_family AND l.hour=tmp.hour