
WITH 
	
	DIST AS (
	SELECT
		DISTINCT ON (DN_ID) *
	FROM
		MV3_0
), TMPDIST AS (
	SELECT
		CASE WHEN DAC_FAMILY IS NULL THEN 'BENIGN' ELSE DAC_FAMILY END as DAC_FAMILY,
	DAC_RANK,
		COUNT(*) AS N,
		COUNT(*) FILTER (WHERE EPS1 > 0.5) AS P1,
		COUNT(*) FILTER (WHERE EPS2 > 0.5) AS P2,
		COUNT(*) FILTER (WHERE EPS3 > 0.5) AS P3,
		COUNT(*) FILTER (WHERE EPS4 > 0.5) AS P4
	FROM
		DIST
	WHERE
-- WL_RANK = 1
	DN_RANK = 1
	GROUP BY DAC_FAMILY, dac_rank
),
 TMP AS (
	SELECT
		CASE WHEN DAC_FAMILY IS NULL THEN 'BENIGN' ELSE DAC_FAMILY END as DAC_FAMILY,
	DAC_RANK,
		COUNT(*) AS N,
		COUNT(*) FILTER (WHERE EPS1 > 0.5) AS P1,
		COUNT(*) FILTER (WHERE EPS2 > 0.5) AS P2,
		COUNT(*) FILTER (WHERE EPS3 > 0.5) AS P3,
		COUNT(*) FILTER (WHERE EPS4 > 0.5) AS P4
	FROM
		MV3_0
	WHERE
	-- WL_RANK = 1
	DN_RANK = 1
	GROUP BY DAC_FAMILY, dac_rank
)
	SELECT
	TD.DAC_FAMILY,
	TD.DAC_RANK,
	T.DAC_FAMILY,
	T.DAC_RANK,
	TD.N as DISTINCT_N,
	T.N,
	TD.P1 AS DISTINCT_P1,
	T.P1,
	TD.P2 AS DISTINCT_P2,
	T.P2,
	TD.P3 AS DISTINCT_P3,
	T.P3,
	TD.P4 AS DISTINCT_P4,
	T.P4,
	ROUND(TD.P1::NUMERIC / TD.N, 2) AS DISTINCT_TPR1,
	ROUND(T.P1::NUMERIC / T.N, 2) AS TPR1,
	ROUND(TD.P2::NUMERIC / TD.N, 2) AS DISTINCT_TPR2,
	ROUND(T.P2::NUMERIC / T.N, 2) AS TPR2,
	ROUND(TD.P3::NUMERIC / TD.N, 2) AS DISTINCT_TPR3,
	ROUND(T.P3::NUMERIC / T.N, 2) AS TPR3,
	ROUND(TD.P4::NUMERIC / TD.N, 2) AS DISTINCT_TPR4,
	ROUND(T.P4::NUMERIC / T.N, 2) AS TPR4
FROM
	TMPDIST TD JOIN TMP T ON TD.dac_family=T.dac_family AND TD.DAC_RANK=T.DAC_RANK