WITH TMP AS (
	SELECT
		DN,
		COUNT(*) AS "N", 
		COUNT(*) FILTER (WHERE TS_BEGIN IS NULL) AS "#∄ts",
		COUNT(*) FILTER (WHERE TS_BEGIN IS NOT NULL) AS "#∃ts",
		COUNT(*) FILTER (WHERE TS_BEGIN IS NULL)
	FROM DAC
	GROUP BY DN
)
SELECT
	COUNT(*) AS "u(DAC.DN)",
	COUNT(*) FILTER (WHERE DN.ID IS NOT NULL) AS "∃(DN.DN)",
	COUNT(*) FILTER (WHERE DN.ID IS NULL)  AS "∄(DN.DN)",
	COUNT(*) FILTER (WHERE "#∃ts"=0) AS "∄ts",
	COUNT(*) FILTER (WHERE "#∄ts"=0) AS "∃ts",
	COUNT(*) FILTER (WHERE DN.ID IS NULL AND "#∃ts"=0) AS "#(∄DN & ∄ts)",
	COUNT(*) FILTER (WHERE DN.ID IS NULL AND "#∄ts"=0) AS "#(∄DN & ∃ts)",
	COUNT(*) FILTER (WHERE DN.ID IS NOT NULL AND "#∃ts"=0) AS "#(∃DN & ∄ts)",
	COUNT(*) FILTER (WHERE DN.ID IS NOT NULL AND "#∄ts"=0) AS "#(∃DN & ∃ts)",
	COUNT(*) FILTER (WHERE DN.ID IS NOT NULL AND "#∃ts"=0 AND WL1.ID IS NULL) AS "#(∃DN & ∄ts & ∄wl)",
	COUNT(*) FILTER (WHERE DN.ID IS NOT NULL AND "#∃ts"=0 AND WL1.ID IS NOT NULL) AS "#(∃DN & ∄ts & ∃wl)",
	COUNT(*) FILTER (WHERE DN.ID IS NOT NULL AND "#∄ts"=0 AND WL1.ID IS NULL) AS "#(∃DN & ∃ts & ∄wl)",
	COUNT(*) FILTER (WHERE DN.ID IS NOT NULL AND "#∄ts"=0 AND WL1.ID IS NOT NULL) AS "#(∃DN & ∃ts & ∃wl)"
FROM
	TMP LEFT JOIN DN ON TMP.DN=DN.DN
	LEFT JOIN WHITELIST1 WL1 ON DN.ID=WL1.DN_ID

