WITH
	DNN AS (
		SELECT
			ID,
			DN
		FROM
			DN
		WHERE
			DN.DN != LOWER(DN.DN)
	),
	DNN_COUNT AS (
		SELECT
			DNN.ID AS ID,
			DNN.DN AS DN,
			ROW_NUMBER() OVER (
				PARTITION BY
					LOWER(DNN.DN)
				ORDER BY
					DNN.DN
			) AS ROW_NUM
		FROM
			DNN
		ORDER BY
			DNN.DN,
			ROW_NUM
	),
	DN_TOCHANGE AS (
		SELECT
			LOWER(DNN_COUNT.DN) AS DN,
			ARRAY_AGG(DNN_COUNT.ID) AS IDS,
			ARRAY_AGG(ROW_NUM)
		FROM
			DNN_COUNT
		WHERE
			ROW_NUM >= 2
		GROUP BY
			LOWER(DNN_COUNT.DN)
	),
	DN_SET AS (
		SELECT
			LOWER(DNN_COUNT.DN) AS DN,
			DNN_COUNT.ID
		FROM
			DNN_COUNT
		WHERE
			ROW_NUM = 1
	),
	DNUPDATE AS (
		SELECT
			*
		FROM
			DN_SET
			JOIN DN_TOCHANGE ON DN_TOCHANGE.DN = DN_SET.DN
	LIMIT 10
	)
SELECT * FROM MESSAGE M2 JOIN DNUPDATE ON M2.DN_ID = ANY (DNUPDATE.IDS) LIMIT 10
-- UPDATE MESSAGE2 M2
-- SET
-- 	DN_ID = DNUPDATE.ID
-- FROM
-- 	DNUPDATE
-- WHERE
-- 	M2.DN_ID = ANY (DNUPDATE.IDS)