WITH

OVERALL AS (
	SELECT
	DN.ID,
	DN.DN,
	WL.RANK_DN,
	WL.RANK_BDN,
	COUNT(*) AS APP,
	SUM(CASE WHEN M.RCODE = 0 THEN 1 ELSE 0 END) AS OK,
	SUM(CASE WHEN M.RCODE = 3 THEN 1 ELSE 0 END) AS NX,

	COUNT(DISTINCT M.PCAP_ID) AS PCAPS,
	array_agg(DISTINCT M.PCAP_ID) AS PCAPS_ID
	
	-- , SUM(CASE WHEN (M.status).malware_type = 'no-malware' THEN 1 ELSE 0 END) AS APP_NIC,
	-- SUM(CASE WHEN (M.status).malware_type = 'dga' THEN 1 ELSE 0 END) AS APP_DGA,
	-- SUM(CASE WHEN (M.status).malware_type = 'non-dga' THEN 1 ELSE 0 END) AS APP_NDGA,
	
	-- SUM(CASE WHEN M.RCODE = 3 and (M.status).malware_type = 'no-malware' THEN 1 ELSE 0 END) AS NX_NIC,
	-- SUM(CASE WHEN M.RCODE = 3 and (M.status).malware_type = 'dga' THEN 1 ELSE 0 END) AS NX_DGA,
	-- SUM(CASE WHEN M.RCODE = 3 and (M.status).malware_type = 'non-dga' THEN 1 ELSE 0 END) AS NX_NONDGA
FROM
MESSAGE AS M
	JOIN PCAP ON M.PCAP_ID = PCAP.ID
	JOIN DN ON M.DN_ID = DN.ID
	JOIN WHITELIST_DN WL ON WL.DN_ID = DN.ID
	WHERE PCAP.INFECTED is true
GROUP BY DN.ID,
	WL.RANK_DN,
	WL.RANK_BDN
-- HAVING COUNT(DISTINCT M.PCAP_ID) = 1 AND WL.RANK_BDN is Null
ORDER BY APP ASC
)
SELECT * FROM OVERALL WHERE 43 = ANY (PCAPS_ID)