WITH M2 AS (
SELECT
	DISTINCT ON (DN_ID) 
	*
FROM
	MESSAGE2 M2
	-- JOIN PCAP ON M2.PCAP_ID = PCAP.ID
	-- LEFT JOIN DAC_DN ON M2.DN_ID = DAC_DN.DN_ID
	-- LEFT JOIN DN_NN ON M2.DN_ID = DN_NN.DN_ID
	WHERE IS_R is TRUE
),
M22 AS (
	SELECT *,
	(DAC_DN.DN_ID is null)::int as N,
	(DAC_DN.DN_ID is not null)::int as P,
	(DN_NN.EPS1 < 0.5 AND DAC_DN.DN_ID is null)::int as tn,
	(DN_NN.EPS1 >= 0.5 AND DAC_DN.DN_ID is not null)::int as tp
	FROM M2
	JOIN PCAP ON M2.PCAP_ID = PCAP.ID
	LEFT JOIN DN_NN_ALL DN_NN ON M2.DN_ID = DN_NN.DN_ID
	LEFT JOIN DAC_DN ON M2.DN_ID = DAC_DN.DN_ID AND ((PCAP.TIME_S_MIN + '00:00:01'::INTERVAL * EXTRACT(EPOCH FROM M2.TIME_S)::DOUBLE PRECISION) >= DAC_DN.TS_BEGIN
	AND (PCAP.TIME_S_MIN + '00:00:01'::INTERVAL * EXTRACT(EPOCH FROM M2.TIME_S)::DOUBLE PRECISION) <= DAC_DN.TS_END)
)
SELECT
	M22.NAME,
	M22.TIME_S_MIN,
	COUNT(*),
	sum(P) as p,
	sum(N) as n,
	SUM(TN) as tn,
	SUM(TP) as tp,
	CASE WHEN SUM(N) > 0 THEN SUM(TN)::double precision/SUM(N) ELSE null END as tnr,
	CASE WHEN SUM(P) > 0 THEN SUM(TP)::double precision/SUM(P) ELSE null END as tpr
FROM
	M22
GROUP BY M22.NAME, M22.TIME_S_MIN
ORDER BY M22.TIME_S_MIN


-- 132626748
-- 16026856

-- 1379624
-- 91424

-- TUTTI CON DISTINCT ON:
-- 7967984
-- 282428

-- SOLO LE REQUESTs CON DISTINCT ON:
-- 240948
-- 7365668

-- SOLO LE RESPONSE CON DISTINCT ON:
-- 282892
-- 7966020