WITH
	MM1 AS (
		SELECT
			M2.*,
			DAC.ID AS DAC2_ID,
			DAC.TS_BEGIN,
			DAC.TS_END,
			(
				(
					PCAP.TIME_S_MIN + INTERVAL '1 second' * M2.SECONDS
				) BETWEEN DAC.TS_BEGIN AND DAC.TS_END
			) AS DAC2_COMPRESO,
			CASE
				WHEN DAC.ID IS NOT NULL THEN (
					CASE
						WHEN (
							(
								PCAP.TIME_S_MIN + INTERVAL '1 second' * M2.SECONDS
							) BETWEEN DAC.TS_BEGIN AND DAC.TS_END
						) THEN 1
						ELSE 2
					END
				)
				ELSE 3
			END AS DACRANK
		FROM
			MESSAGE2_IT16_0_COMPACT M2
			JOIN PCAP ON M2.PCAP_ID = PCAP.ID
			JOIN DN ON M2.DN_ID = DN.ID
			LEFT JOIN DAC_IT16 DAC ON DN.DN = DAC.DN
	),
	MM2 AS (
		SELECT
			MM1.*,
			ROW_NUMBER() OVER (
				PARTITION BY
					MM1.ID
				ORDER BY
					MM1.DACRANK,
					MM1.DAC2_ID
			) AS RN_DACRANK
		FROM
			MM1
	)
SELECT
	COUNT(*),
	COUNT(DISTINCT MM2.ID),
	SUM((RN_DACRANK = 1)::int),
	SUM((RN_DACRANK > 1)::int)
FROM
	MM2
-- ORDER BY
-- 	ID,
-- 	MM2.DN_ID,
-- 	RN_DACRANK DESC